---
title: "examples"
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
```

```{r}
library(fsmglobal)
library(gt)
library(dplyr)
library(ggplot2)
```

```{r}
tbl_emptying_demand_global <- fsmglobal |> 
  group_by(emptying_method) |> 
  summarise(
    sum_population_emptying_method = sum(population_emptying_method)
  ) |> 
  mutate(
    percent = sum_population_emptying_method / 
      sum(sum_population_emptying_method) * 100
  )
```


```{r}
tbl_emptying_demand_global |> 
  janitor::adorn_totals() |>
  
  # use gt R package to prepare a table
  gt(rowname_col = "emptying_method") |>
  tab_header(title = md("**Demand for faecal sludge emptying services**"), 
             subtitle = "summarised for 175 countries") |> 
  fmt_number(columns = "sum_population_emptying_method", decimals = 0) |> 
  fmt_percent(columns = "percent", decimals = 0, scale_values = FALSE) |> 
  cols_label(sum_population_emptying_method = "population") 
```


